# Path: android/app/proguard-rules.pro
-keep class com.chaquo.** { *; }
-keep class dagger.hilt.** { *; }
-keep class okhttp3.** { *; }
-keep class androidx.room.** { *; }
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.** { *; }
-keep class io.flutter.util.** { *; }
-keep class io.flutter.view.** { *; }
-keep class io.flutter.** { *; }
-keep class io.flutter.plugins.** { *; }
-dontwarn com.chaquo.**
